app/urls.py
from django.contrib import admin
from django.urls.conf import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/user/urls.py
from app.settings import DRF_V1_STR
from dj_rest_auth.registration.views import ConfirmEmailView, VerifyEmailView
from django.urls import path
from django.urls.conf import include, path

from .views import (CustomEmailConfirmationView, CustomLoginView,
                    CustomPasswordResetView, CustomPasswordSetView,
                    CustomRegisterView)

app_name = "accounts"

urlpatterns = [
    path("accounts/", include('dj_rest_auth.urls')),
    # The confirm_email path below should always be placed 
    # above the signup view otherwise there will be a template error
    path("accounts/confirm-email/<str:key>/",
        ConfirmEmailView.as_view(), name='confirm_email',
    ),
    path("accounts/signin/",
         CustomLoginView.as_view(), name="login"),
    path("accounts/password/reset/", CustomPasswordResetView.as_view(),
         name='password_reset'),
    path("accounts/password/set/",
         CustomPasswordSetView.as_view(), name="set_password"),
    path(f"accounts/signup/", CustomRegisterView.as_view(),
         name='signup'),
    path("accounts/confirm-email/", VerifyEmailView.as_view(),
         name='email_verification_sent'),
    path("accounts/resend-email/",
         CustomEmailConfirmationView.as_view(), name="resend_email"),

]

app/templates/accounts/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

app/templates/accounts/email_confirm.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'accounts:confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

app/templates/accounts/login.html
{% load custom_tags %}
<h2>Log In from Accounts {{ request.path }}</h2>

{% url "accounts:login" as login_url %}
<form method="POST" action="{{ login_url }}?next={{request.path}}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
</form>

<div>
  <a href="{% url 'accounts:reset_password' %}">Log In</a>
</div>


 
{% comment %}
{% load custom_tags %}
<h2>Log In from Accounts {% url_path request.META.HTTP_REFERER %}</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="hidden" name="next" value="{% url_path request.META.HTTP_REFERER %}"/>
  <button type="submit">Log In</button>
</form>

<div>
  <a href="{% url 'accounts:reset_password' %}">Log In</a>
</div>
{% endcomment %}

app/templates/accounts/logout.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'accounts:logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

app/templates/accounts/password_change.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'accounts:change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
        <a href="{% url 'accounts:reset_password' %}">{% trans "Forgot Password?" %}</a>
    </form>
{% endblock %}

app/templates/accounts/password_reset.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "accounts/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'accounts:reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

app/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
    <h1>{% trans "Password Reset" %}</h1>
    
    {% if user.is_authenticated %}
    {% include "accounts/snippets/already_logged_in.html" %}
    {% endif %}
    
    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% endblock %}

app/templates/accounts/password_reset_from_key.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Custom Change Password" %}{% endblock %}

{% block content %}
    <h1>{% if token_fail %}{% trans "Custom Bad Token" %}{% else %}{% trans "Change Password" %}{% endif %}</h1>

    {% if token_fail %}
        {% url 'accounts:reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

app/templates/accounts/password_reset_from_key_done.html
{% extends "accounts/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

app/templates/accounts/password_set.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Set Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Set Password" %}</h1>

    <form method="POST" action="{% url 'accounts:set_password' %}" class="password_set">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="action" value="{% trans 'Set Password' %}"/>
    </form>
{% endblock %}

app/templates/accounts/signup.html
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>

app/templates/accounts/verification_sent.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
    <h1>{% trans "Verify Your E-mail Address" %}</h1>

    <p>{% blocktrans %}Are you There? We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

{% endblock %}